// <auto-generated />
using Jwt2._0Authentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jwt2._0Authentication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210617180713_Added_refreshTokens_table")]
    partial class Added_refreshTokens_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jwt2._0Authentication.Data.Entities.Other.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Jwt2._0Authentication.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            Password = "$2a$11$k6lTGBFMXqMs3P3kd0Bw6..I.7gcb1VBuAcugu68ODf35kOo4os1i",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "test1@gmail.com",
                            Name = "Dominik",
                            Password = "$2a$11$MI2ZgcIGUraqFGjWSCThvu.LMNvaLXbNU3Ko1EkdPUftHXIH6snOm",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "test2@gmail.com",
                            Name = "Vladislav",
                            Password = "$2a$11$R7hJennV2BQsllkIS0Flber8LXf6RtHJjATUPFHEw2oRvWUATJmqa",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Jwt2._0Authentication.Data.Entities.Other.RefreshToken", b =>
                {
                    b.HasOne("Jwt2._0Authentication.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
