// <auto-generated />
using Jwt2._0Authentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jwt2._0Authentication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210617150823_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jwt2._0Authentication.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            Password = "$2a$11$8xSqmzBuQU3RcGwmoFcc.OBWKc1bJ98ob0oXI1w4TpEW2FcMxYT9e",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "test1@gmail.com",
                            Name = "Dominik",
                            Password = "$2a$11$lZavkYYBxELJ4q2MpEH4BOMDVnKuBqP/XrYEHXgv5fJbkFiwK2tHW",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "test2@gmail.com",
                            Name = "Vladislav",
                            Password = "$2a$11$gcXptLkNebHviE47/Pd49.njr8cYmXWvGLu981CLcutE372luxGbG",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
